name = "etherith-production"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
# Discord OAuth Configuration
DISCORD_CLIENT_ID = "1372269269143916544"
DISCORD_REDIRECT_URI = "https://etherith-production.pages.dev/dashboard.html"
